export type TypeAction = 'of' | 'bc' | 'vae' | 'cfa';

export type DocCategory = 'processus' | 'preuve';

export interface PreuveItem {
  id: string;
  label: string;
  description?: string;
  /** Is this a dynamic proof that must be collected (not generated by AI)? */
  dynamic: boolean;
}

export interface Indicateur {
  id: string;
  /** Numéro officiel (1 à 32) */
  numero: number;
  titre: string;
  description: string;
  /** Documents-processus générables par l'IA */
  docs_types: string[];
  /** Preuves attendues par l'auditeur */
  preuves: PreuveItem[];
  /** Types d'actions auxquels cet indicateur s'applique (vide = tous) */
  appliesToTypes?: TypeAction[];
  conditionalNote?: string;
  /** Spécifique nouvel entrant ? */
  nouveauEntrantOnly?: boolean;
  /** Spécifique renouvellement ? */
  renouvellementOnly?: boolean;
}

export interface Critere {
  id: string;
  titre: string;
  indicateurs: Record<string, Indicateur>;
}

export type RNQData = Record<string, Critere>;

function preuve(id: string, label: string, dynamic = false, description?: string): PreuveItem {
  return { id, label, dynamic, description };
}

export const RNQ_V9: RNQData = {
  critere1: {
    id: "critere1",
    titre: "Les conditions d'information du public sur les prestations proposées, les délais pour y accéder et les résultats obtenus",
    indicateurs: {
      "I1": {
        id: "I1", numero: 1,
        titre: "Information accessible au public",
        description: "Le prestataire diffuse une information accessible au public, détaillée et vérifiable sur les prestations proposées : prérequis, objectifs, durée, modalités et délais d'accès, tarifs, contacts, méthodes mobilisées et modalités d'évaluation, accessibilité aux personnes handicapées.",
        docs_types: ["Fiche_Information_Prealable.docx", "CGV.docx", "Programme_Formation.docx"],
        preuves: [
          preuve("I1-P1", "Site internet à jour", true, "Capture d'écran ou URL du site"),
          preuve("I1-P2", "Plaquette commerciale / catalogue"),
          preuve("I1-P3", "CGV signées", true, "Exemplaire signé par un bénéficiaire"),
          preuve("I1-P4", "Programme de formation"),
        ],
      },
      "I2": {
        id: "I2", numero: 2,
        titre: "Indicateurs de résultats diffusés",
        description: "Le prestataire diffuse des indicateurs de résultats adaptés à la nature des prestations mises en œuvre et des publics accueillis.",
        docs_types: ["Tableau_Indicateurs_Resultats.xlsx", "Bilan_Activite.docx"],
        preuves: [
          preuve("I2-P1", "Tableau de bord des résultats", true, "Taux de satisfaction, abandon, réussite"),
          preuve("I2-P2", "Rapport d'activité / bilan annuel", true),
          preuve("I2-P3", "Publication des résultats sur le site", true),
        ],
      },
      "I3": {
        id: "I3", numero: 3,
        titre: "Information sur les certifications et taux d'obtention",
        description: "Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il informe sur les taux d'obtention des certifications préparées, les possibilités de valider un/ou des blocs de compétences, ainsi que sur les équivalences, passerelles, suites de parcours et les débouchés.",
        appliesToTypes: ['of', 'cfa'],
        conditionalNote: "Uniquement si formations certifiantes",
        docs_types: ["Information_Certifications.docx", "Tableau_Taux_Obtention.xlsx"],
        preuves: [
          preuve("I3-P1", "Fiches RNCP des certifications visées", true),
          preuve("I3-P2", "Taux d'obtention publiés", true),
          preuve("I3-P3", "Information passerelles et débouchés"),
        ],
      },
    },
  },

  critere2: {
    id: "critere2",
    titre: "L'identification précise des objectifs des prestations proposées et l'adaptation de ces prestations aux publics bénéficiaires lors de la conception des prestations",
    indicateurs: {
      "I4": {
        id: "I4", numero: 4,
        titre: "Analyse des besoins du bénéficiaire",
        description: "Le prestataire analyse le besoin du bénéficiaire en lien avec l'entreprise et/ou le financeur concerné(s).",
        docs_types: ["Grille_Analyse_Besoin.docx", "Fiche_Diagnostic_Prealable.docx"],
        preuves: [
          preuve("I4-P1", "Grille d'analyse des besoins"),
          preuve("I4-P2", "Comptes rendus d'entretiens préalables", true),
          preuve("I4-P3", "Dossiers d'admission remplis", true),
        ],
      },
      "I5": {
        id: "I5", numero: 5,
        titre: "Objectifs opérationnels et évaluables",
        description: "Le prestataire définit les objectifs opérationnels et évaluables de la prestation.",
        docs_types: ["Fiche_Objectifs_Operationnels.docx"],
        preuves: [
          preuve("I5-P1", "Fiche objectifs opérationnels"),
          preuve("I5-P2", "Compétences visées formalisées"),
        ],
      },
      "I6": {
        id: "I6", numero: 6,
        titre: "Contenus et modalités adaptés aux objectifs",
        description: "Le prestataire établit les contenus et les modalités de mise en œuvre de la prestation, adaptés aux objectifs définis et aux publics bénéficiaires.",
        docs_types: ["Sequencage_Pedagogique.docx", "Guide_Modalites_FOAD.docx"],
        preuves: [
          preuve("I6-P1", "Séquençage pédagogique / déroulé"),
          preuve("I6-P2", "Supports pédagogiques", true),
        ],
      },
      "I7": {
        id: "I7", numero: 7,
        titre: "Adéquation contenu / certification visée",
        description: "Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il s'assure de l'adéquation du ou des contenus de la prestation aux exigences de la certification visée.",
        appliesToTypes: ['of', 'cfa'],
        conditionalNote: "Uniquement si formations certifiantes",
        docs_types: ["Tableau_Croise_Contenu_RNCP.docx"],
        preuves: [
          preuve("I7-P1", "Tableau croisé contenu / référentiel RNCP"),
          preuve("I7-P2", "Habilitation ou convention avec le certificateur", true),
        ],
      },
      "I8": {
        id: "I8", numero: 8,
        titre: "Positionnement et évaluation des acquis à l'entrée",
        description: "Le prestataire détermine les procédures de positionnement et d'évaluation des acquis à l'entrée de la prestation.",
        docs_types: ["Procedure_Positionnement_Entree.docx", "Grille_Evaluation_Acquis_Entree.xlsx"],
        preuves: [
          preuve("I8-P1", "Procédure de positionnement"),
          preuve("I8-P2", "Grilles d'évaluation à l'entrée"),
          preuve("I8-P3", "Résultats de positionnement remplis", true),
        ],
      },
    },
  },

  critere3: {
    id: "critere3",
    titre: "L'adaptation aux publics bénéficiaires des prestations et des modalités d'accueil, d'accompagnement, de suivi et d'évaluation mises en œuvre",
    indicateurs: {
      "I9": {
        id: "I9", numero: 9,
        titre: "Information sur les conditions de déroulement",
        description: "Le prestataire informe les publics bénéficiaires des conditions de déroulement de la prestation.",
        docs_types: ["Livret_Accueil.docx", "Reglement_Interieur.docx", "Convocation_Formation.docx"],
        preuves: [
          preuve("I9-P1", "Livret d'accueil"),
          preuve("I9-P2", "Règlement intérieur"),
          preuve("I9-P3", "Convocations envoyées", true),
        ],
      },
      "I10": {
        id: "I10", numero: 10,
        titre: "Adaptation de la prestation et du suivi",
        description: "Le prestataire met en œuvre et adapte la prestation, l'accompagnement et le suivi aux publics bénéficiaires.",
        docs_types: ["Fiche_Suivi_Individuel.docx", "Livret_Suivi_Pedagogique.docx"],
        preuves: [
          preuve("I10-P1", "Fiches de suivi individuelles remplies", true),
          preuve("I10-P2", "Feuilles d'émargement", true, "Signées par les apprenants et le formateur"),
          preuve("I10-P3", "Livret de suivi pédagogique"),
        ],
      },
      "I11": {
        id: "I11", numero: 11,
        titre: "Évaluation de l'atteinte des objectifs",
        description: "Le prestataire évalue l'atteinte par les publics bénéficiaires des objectifs de la prestation.",
        docs_types: ["Grille_Evaluation_Mi_Parcours.docx", "Grille_Evaluation_Fin_Formation.docx"],
        preuves: [
          preuve("I11-P1", "Grilles d'évaluation mi-parcours"),
          preuve("I11-P2", "Grilles d'évaluation fin de formation"),
          preuve("I11-P3", "Résultats d'évaluation remplis", true),
          preuve("I11-P4", "Attestations de fin de formation", true),
        ],
      },
      "I12": {
        id: "I12", numero: 12,
        titre: "Engagement des bénéficiaires et prévention des ruptures",
        description: "Le prestataire décrit et met en œuvre les mesures pour favoriser l'engagement des bénéficiaires et prévenir les ruptures de parcours.",
        docs_types: ["Procedure_Prevention_Ruptures.docx", "Fiche_Relance_Apprenant.docx"],
        preuves: [
          preuve("I12-P1", "Procédure de gestion des abandons"),
          preuve("I12-P2", "Listing des relances effectuées", true),
          preuve("I12-P3", "Statistiques d'abandon", true),
        ],
      },
      "I13": {
        id: "I13", numero: 13,
        titre: "Coordination des apprentissages en alternance",
        description: "Pour les formations en alternance, le prestataire, en lien avec l'entreprise, anticipe avec l'apprenant les missions confiées, à court, moyen et long terme, et assure la coordination et la progressivité des apprentissages réalisés en centre de formation et en entreprise.",
        appliesToTypes: ['cfa'],
        conditionalNote: "Spécifique CFA / alternance",
        docs_types: ["Carnet_Liaison_CFA_Entreprise.docx", "CR_Visite_Entreprise.docx"],
        preuves: [
          preuve("I13-P1", "Carnet de liaison CFA-Entreprise"),
          preuve("I13-P2", "CR de visites en entreprise", true),
          preuve("I13-P3", "Plannings alternance", true),
        ],
      },
      "I14": {
        id: "I14", numero: 14,
        titre: "Accompagnement socio-professionnel et citoyenneté",
        description: "Le prestataire met en œuvre un accompagnement socio-professionnel, éducatif et relatif à l'exercice de la citoyenneté.",
        appliesToTypes: ['cfa'],
        conditionalNote: "Spécifique CFA",
        docs_types: ["Programme_Accompagnement_Socio_Pro.docx"],
        preuves: [
          preuve("I14-P1", "Programme d'accompagnement socio-pro"),
          preuve("I14-P2", "Planning d'ateliers culturels/sportifs", true),
          preuve("I14-P3", "CR d'actions de citoyenneté", true),
        ],
      },
      "I15": {
        id: "I15", numero: 15,
        titre: "Droits et devoirs des apprentis, santé et sécurité",
        description: "Le prestataire informe les apprentis de leurs droits et devoirs en tant qu'apprentis et salariés ainsi que des règles applicables en matière de santé et de sécurité en milieu professionnel.",
        appliesToTypes: ['cfa'],
        conditionalNote: "Spécifique CFA",
        docs_types: ["Information_Droits_Devoirs_Apprentis.docx"],
        preuves: [
          preuve("I15-P1", "Support d'information droits et devoirs"),
          preuve("I15-P2", "Attestation de remise du livret", true),
          preuve("I15-P3", "Règlement intérieur signé", true),
        ],
      },
      "I16": {
        id: "I16", numero: 16,
        titre: "Conditions de présentation à la certification",
        description: "Lorsque le prestataire met en œuvre des formations conduisant à une certification professionnelle, il s'assure que les conditions de présentation des bénéficiaires à la certification respectent les exigences formelles de l'autorité de certification.",
        appliesToTypes: ['of', 'cfa'],
        conditionalNote: "Uniquement si formations certifiantes",
        docs_types: ["Procedure_Presentation_Certification.docx"],
        preuves: [
          preuve("I16-P1", "Procédure de présentation aux examens"),
          preuve("I16-P2", "PV de sessions d'examen", true),
          preuve("I16-P3", "Habilitation à évaluer", true),
        ],
      },
    },
  },

  critere4: {
    id: "critere4",
    titre: "L'adéquation des moyens pédagogiques, techniques et d'encadrement aux prestations mises en œuvre",
    indicateurs: {
      "I17": {
        id: "I17", numero: 17,
        titre: "Moyens humains et techniques adaptés",
        description: "Le prestataire met à disposition ou s'assure de la mise à disposition des moyens humains et techniques adaptés et d'un environnement approprié (conditions, locaux, équipements, plateaux techniques…).",
        docs_types: ["Inventaire_Moyens.docx", "DUERP.docx", "Registre_Accessibilite.docx"],
        preuves: [
          preuve("I17-P1", "Inventaire des moyens matériels"),
          preuve("I17-P2", "DUERP (Document Unique)", true),
          preuve("I17-P3", "Registre d'accessibilité", true),
          preuve("I17-P4", "Bail / contrat de location des locaux", true),
        ],
      },
      "I18": {
        id: "I18", numero: 18,
        titre: "Coordination des intervenants",
        description: "Le prestataire mobilise et coordonne les différents intervenants internes et/ou externes (pédagogiques, administratifs, logistiques, commerciaux…).",
        docs_types: ["Fiche_Poste_Formateur.docx", "Planning_Coordination.docx"],
        preuves: [
          preuve("I18-P1", "Organigramme fonctionnel"),
          preuve("I18-P2", "Fiches de poste"),
          preuve("I18-P3", "CR de réunions d'équipe", true),
        ],
      },
      "I19": {
        id: "I19", numero: 19,
        titre: "Ressources pédagogiques mises à disposition",
        description: "Le prestataire met à disposition du bénéficiaire des ressources pédagogiques et permet à celui-ci de se les approprier.",
        docs_types: ["Catalogue_Ressources_Pedagogiques.docx", "Procedure_Acces_LMS.docx"],
        preuves: [
          preuve("I19-P1", "Catalogue des ressources pédagogiques"),
          preuve("I19-P2", "Procédure d'accès au LMS"),
          preuve("I19-P3", "Captures d'écran de la plateforme", true),
        ],
      },
      "I20": {
        id: "I20", numero: 20,
        titre: "Personnel dédié : mobilité, handicap, conseil de perfectionnement",
        description: "Le prestataire dispose d'un personnel dédié à l'appui à la mobilité nationale et internationale, d'un référent handicap et d'un conseil de perfectionnement.",
        appliesToTypes: ['cfa'],
        conditionalNote: "Spécifique CFA",
        docs_types: ["PV_Conseil_Perfectionnement.docx", "PV_Nomination_Referent_Handicap.docx"],
        preuves: [
          preuve("I20-P1", "PV du conseil de perfectionnement", true),
          preuve("I20-P2", "Nomination du référent handicap"),
          preuve("I20-P3", "Nomination du référent mobilité"),
          preuve("I20-P4", "CR du conseil de perfectionnement", true),
        ],
      },
    },
  },

  critere5: {
    id: "critere5",
    titre: "La qualification et le développement des connaissances et compétences des personnels chargés de mettre en œuvre les prestations",
    indicateurs: {
      "I21": {
        id: "I21", numero: 21,
        titre: "Compétences des intervenants",
        description: "Le prestataire détermine, mobilise et évalue les compétences des différents intervenants internes et/ou externes, adaptées aux prestations.",
        docs_types: ["Grille_Competences_Intervenants.docx", "Procedure_Recrutement_Formateurs.docx"],
        preuves: [
          preuve("I21-P1", "CV des formateurs", true),
          preuve("I21-P2", "Grille de compétences des intervenants"),
          preuve("I21-P3", "Procédure de recrutement"),
          preuve("I21-P4", "Contrats / lettres de mission", true),
        ],
      },
      "I22": {
        id: "I22", numero: 22,
        titre: "Développement des compétences des salariés",
        description: "Le prestataire entretient et développe les compétences de ses salariés, adaptées aux prestations qu'il délivre.",
        docs_types: ["Plan_Developpement_Competences.xlsx", "Procedure_Entretien_Professionnel.docx"],
        preuves: [
          preuve("I22-P1", "Plan de développement des compétences"),
          preuve("I22-P2", "CR d'entretiens professionnels", true),
          preuve("I22-P3", "Attestations de formation des formateurs", true),
        ],
      },
    },
  },

  critere6: {
    id: "critere6",
    titre: "L'inscription et l'investissement du prestataire dans son environnement professionnel",
    indicateurs: {
      "I23": {
        id: "I23", numero: 23,
        titre: "Veille légale et réglementaire",
        description: "Le prestataire réalise une veille légale et réglementaire sur le champ de la formation professionnelle et en exploite les enseignements.",
        docs_types: ["Procedure_Veille_Juridique.docx", "Tableau_Veille_Legale.xlsx"],
        preuves: [
          preuve("I23-P1", "Procédure de veille juridique"),
          preuve("I23-P2", "Tableau de veille à jour", true),
          preuve("I23-P3", "Preuve d'abonnements / newsletters", true),
        ],
      },
      "I24": {
        id: "I24", numero: 24,
        titre: "Veille sur les compétences, métiers et emplois",
        description: "Le prestataire réalise une veille sur les évolutions des compétences, des métiers et des emplois dans ses secteurs d'intervention et en exploite les enseignements.",
        docs_types: ["Tableau_Veille_Metiers.xlsx"],
        preuves: [
          preuve("I24-P1", "Tableau de veille métiers", true),
          preuve("I24-P2", "CR de participation à des salons / conférences", true),
        ],
      },
      "I25": {
        id: "I25", numero: 25,
        titre: "Veille sur les innovations pédagogiques et technologiques",
        description: "Le prestataire réalise une veille sur les innovations pédagogiques et technologiques permettant une évolution de ses prestations et en exploite les enseignements.",
        docs_types: ["Tableau_Veille_Innovations.xlsx"],
        preuves: [
          preuve("I25-P1", "Tableau de veille innovations", true),
          preuve("I25-P2", "Preuve de mise en œuvre d'une innovation", true),
        ],
      },
      "I26": {
        id: "I26", numero: 26,
        titre: "Accueil et accompagnement des publics en situation de handicap",
        description: "Le prestataire mobilise les expertises, outils et réseaux nécessaires pour accueillir, accompagner/former ou orienter les publics en situation de handicap.",
        docs_types: ["Convention_Partenariat_Handicap.docx", "Liste_Partenaires_Handicap.docx"],
        preuves: [
          preuve("I26-P1", "Liste des partenaires handicap"),
          preuve("I26-P2", "Convention Agefiph / MDPH / Cap emploi", true),
          preuve("I26-P3", "Charte d'accessibilité"),
          preuve("I26-P4", "Exemples d'aménagements réalisés", true),
        ],
      },
      "I27": {
        id: "I27", numero: 27,
        titre: "Sous-traitance et portage salarial",
        description: "Lorsque le prestataire fait appel à la sous-traitance ou au portage salarial, il s'assure du respect de la conformité au présent référentiel.",
        docs_types: ["Charte_Qualite_Sous_Traitants.docx", "Contrat_Sous_Traitance.docx"],
        preuves: [
          preuve("I27-P1", "Charte qualité sous-traitants"),
          preuve("I27-P2", "Contrats de sous-traitance signés", true),
          preuve("I27-P3", "Vérification Qualiopi du sous-traitant", true),
        ],
      },
      "I28": {
        id: "I28", numero: 28,
        titre: "Réseau de partenaires socio-économiques",
        description: "Lorsque les prestations dispensées au bénéficiaire comprennent des périodes de formation en situation de travail, le prestataire mobilise son réseau de partenaires socio-économiques pour co-construire l'ingénierie de formation et favoriser l'accueil en entreprise.",
        appliesToTypes: ['of', 'cfa'],
        conditionalNote: "Si FEST ou alternance",
        docs_types: ["Convention_Partenariat_Entreprise.docx", "Liste_Entreprises_Partenaires.xlsx"],
        preuves: [
          preuve("I28-P1", "Conventions de partenariat entreprise"),
          preuve("I28-P2", "Liste des entreprises partenaires", true),
          preuve("I28-P3", "CR de comités de pilotage", true),
        ],
      },
      "I29": {
        id: "I29", numero: 29,
        titre: "Insertion professionnelle et poursuite d'études",
        description: "Le prestataire développe des actions qui concourent à l'insertion professionnelle ou la poursuite d'étude par la voie de l'apprentissage ou par toute autre voie permettant de développer leurs connaissances et leurs compétences.",
        appliesToTypes: ['cfa'],
        conditionalNote: "Spécifique CFA",
        docs_types: ["Programme_Actions_Insertion.docx"],
        preuves: [
          preuve("I29-P1", "Programme d'actions d'insertion"),
          preuve("I29-P2", "Statistiques d'insertion professionnelle", true),
          preuve("I29-P3", "CR de forums / salons organisés", true),
        ],
      },
    },
  },

  critere7: {
    id: "critere7",
    titre: "Le recueil et la prise en compte des appréciations et des réclamations formulées par les parties prenantes aux prestations délivrées",
    indicateurs: {
      "I30": {
        id: "I30", numero: 30,
        titre: "Recueil des appréciations des parties prenantes",
        description: "Le prestataire recueille les appréciations des parties prenantes : bénéficiaires, financeurs, équipes pédagogiques et entreprises concernées.",
        docs_types: ["Questionnaire_Satisfaction_Apprenti.docx", "Questionnaire_Satisfaction_Entreprise.docx", "Procedure_Recueil_Appreciations.docx"],
        preuves: [
          preuve("I30-P1", "Questionnaires de satisfaction"),
          preuve("I30-P2", "Synthèse des résultats de satisfaction", true),
          preuve("I30-P3", "Enquêtes à froid (6 mois)", true),
        ],
      },
      "I31": {
        id: "I31", numero: 31,
        titre: "Traitement des réclamations et des aléas",
        description: "Le prestataire met en œuvre des modalités de traitement des difficultés rencontrées par les parties prenantes, des réclamations exprimées par ces dernières, des aléas survenus en cours de prestation.",
        docs_types: ["Procedure_Traitement_Reclamations.docx", "Registre_Reclamations.xlsx"],
        preuves: [
          preuve("I31-P1", "Procédure de traitement des réclamations"),
          preuve("I31-P2", "Registre des réclamations", true, "Avec suivi des actions correctives"),
          preuve("I31-P3", "Médiateur identifié"),
        ],
      },
      "I32": {
        id: "I32", numero: 32,
        titre: "Mesures d'amélioration continue",
        description: "Le prestataire met en œuvre des mesures d'amélioration à partir de l'analyse des appréciations et des réclamations.",
        docs_types: ["Procedure_Amelioration_Continue.docx", "Plan_Action_Amelioration.xlsx"],
        preuves: [
          preuve("I32-P1", "Procédure d'amélioration continue"),
          preuve("I32-P2", "Plan d'actions d'amélioration", true),
          preuve("I32-P3", "Bilan annuel d'amélioration", true),
        ],
      },
    },
  },
};

// ── Helper functions ──

export function getAllIndicateurs(): Indicateur[] {
  return Object.values(RNQ_V9).flatMap(critere =>
    Object.values(critere.indicateurs)
  );
}

export function getIndicateurById(id: string): Indicateur | undefined {
  for (const critere of Object.values(RNQ_V9)) {
    if (critere.indicateurs[id]) return critere.indicateurs[id];
  }
  return undefined;
}

export function getCritereForIndicateur(indicateurId: string): Critere | undefined {
  return Object.values(RNQ_V9).find(c => indicateurId in c.indicateurs);
}

/** Vérifie si un indicateur s'applique aux types sélectionnés */
export function indicateurAppliesToTypes(indicateurId: string, selectedTypes: TypeAction[]): boolean {
  if (!selectedTypes || selectedTypes.length === 0) return true;
  const ind = getIndicateurById(indicateurId);
  if (!ind?.appliesToTypes || ind.appliesToTypes.length === 0) return true;
  return ind.appliesToTypes.some(t => selectedTypes.includes(t));
}

/** Retourne la note conditionnelle d'un indicateur */
export function getIndicateurTypeNote(indicateurId: string): string | undefined {
  return getIndicateurById(indicateurId)?.conditionalNote;
}

/** Get dynamic proofs (those that need manual collection) for an indicateur */
export function getDynamicPreuves(indicateurId: string): PreuveItem[] {
  const ind = getIndicateurById(indicateurId);
  return ind?.preuves.filter(p => p.dynamic) || [];
}

/** Get process-document proofs (generatable by AI) for an indicateur */
export function getProcessPreuves(indicateurId: string): PreuveItem[] {
  const ind = getIndicateurById(indicateurId);
  return ind?.preuves.filter(p => !p.dynamic) || [];
}

export const CRITERE_ICONS = {
  critere1: "Globe",
  critere2: "Target",
  critere3: "Users",
  critere4: "Wrench",
  critere5: "GraduationCap",
  critere6: "Network",
  critere7: "MessageSquare",
} as const;

export const CRITERE_COLORS = {
  critere1: "216 72% 30%",
  critere2: "190 60% 38%",
  critere3: "28 80% 52%",
  critere4: "145 50% 36%",
  critere5: "265 50% 48%",
  critere6: "340 55% 48%",
  critere7: "45 75% 48%",
} as const;
